/**
*
* Name: HWGit_FirstClass
*
* @author         Marc Saelzler
*                 H&W Consult GmbH
*                 Bahnhofstr. 3
*                 21244 Buchholz i.d.N.
*                 http://www.hundw.com
*
* @description    First HWGit class.
*
*
* Used Objects: (Objects, StaticResources, Documents)
* 
*
* Used Classes: (Classes, Trigger, Pages)
* 
*
* @date           2012-12-12
*
* Timeline:
* Name 				DateTime 				Version         Description
* Marc Saelzler 	2012-12-12 12:17 (CET) 	1.0				First description text.
*/

public class HWGit_FirstClass
{
	// +++++++++++++++++++++	Inner Classes	++++++++++++++++++++++++++++++ /* 1 */
	


	// +++++++++++++++++++++	ClassVariables	++++++++++++++++++++++++++++++ /* 2 */
	


	// +++++++++++++++++++++	Attributes/Getter-Setter	++++++++++++++++++++++++++++++ /* 3 */
	


	// +++++++++++++++++++++	Constructor		++++++++++++++++++++++++++++++ /* 4 */
	public HWGit_FirstClass()
	{
		
	}


	// +++++++++++++++++++++	Methods		++++++++++++++++++++++++++++++ /* 5 */
	

}